// @flow

// leave off @2x/@3x
const images = {
  backButton: require('../Images/back-btn.png'),
  background: require('../Images/bkgrd-gradient.png'),
  clearLogo: require('../Images/login-logo.png'),
  closeButtonGray: require('../Images/close-btn-gray.png'),
  closeIconBlue: require('../Images/close-icon-blue.png'),
  closeIconWhite: require('../Images/close-icon-white.png'),
  clouds: require('../Images/clouds.png'),
  cityscape: require('../Images/cityscape.png'),
  confirmationUser: require('../Images/user-id-icon-yellow.png'),
  confirmationLogin: require('../Images/green-continue-btn.png'),
  benefits: require('../Images/benefits.png'),
  claims: require('../Images/claims.png'),
  claimsSolo: require('../Images/claimsSolo.png'),
  hsa: require('../Images/hsa.png'),
  idcard: require('../Images/id-card.png'),
  payment: require('../Images/payment.png'),
  myaccount: require('../Images/my-account.png'),
  resources: require('../Images/resources.png'),
  support: require('../Images/support.png'),
  findItButton: require('../Images/find-it-btn.png'),
  forms: require('../Images/forms.png'),
  hsaBg: require('../Images/hsa-graphic.png'),
  // hsaHeader: require('../Images/hsa-hdr.png'),
  iAgree: require('../Images/agree-btn.png'),
  idCardBack: require('../Images/id-card-back.png'),
  idCardFront: require('../Images/id-card-front.png'),
  infoIcon: require('../Images/info-icon-gray.png'),
  errorPage: require('../Images/error-pg.png'),
  errorBackButton: require('../Images/error-go-back-btn.png'),
  // loginButton: require('../Images/login-screen-login-btn-blue.png'),
  loginButtonGreen: require('../Images/login-btn-green.png'),
  loginLogo: require('../Images/login-logo.png'),
 // loginNowButton: require('../Images/login-now-btn-dk-blue.png'),
  loginNowButtonGreen: require('../Images/login-now-btn.png'),
  logout: require('../Images/logout-btn-green.png'),
  myPlanbg: require('../Images/health-plan-bkgrd.png'),
  nextButton: require('../Images/next-btn.png'),
  nextButtonGreen: require('../Images/next-btn-green.png'),
  regCompletion: require('../Images/reg-complete-hdr.png'),
  regcompletehdr: require('../Images/reg-complete-hdr.png'),
  registrationStep1Hdr: require('../Images/registration-step1-header.png'),
  registrationStep2Hdr: require('../Images/registration-step2-header.png'),
  registrationStep3Hdr: require('../Images/registration-step3-header.png'),
  registrationStep4Hdr: require('../Images/registration-step4-header.png'),
  setupPinButtonGray: require('../Images/setup-pin-btn-gray.png'),
  setupTouchButtonBlue: require('../Images/setup-touch-btn-blue.png'),
  setupTouchButtonGray: require('../Images/setup-touch-btn-gray.png'),
  splashLogo: require('../Images/splash-logo.png'),
  themeHeader: require('../Images/dashboard-hdr.png'),
  themeLogo: require('../Images/theme-logo.png'),
  doctor: require('../Images/doctor.gif'),
  criticalillness: require('../Images/criticalillness.gif'),
  lab: require('../Images/lab.gif'),
  hospital: require('../Images/hospital.gif'),
  pharmacy: require('../Images/pharmacy.gif'),
  urgentcare: require('../Images/urgent-care.gif'),
  hearthand: require('../Images/heart-hand.gif'),
  getResultsButton: require('../Images/get-results-btn.png'),
  saveLocationButton: require('../Images/save-location.png'),
  viewListButton: require('../Images/view-list-btn.png'),
  mapUnselectedPin: require('../Images/map-unselected.png'),
  mapSelectedPin: require('../Images/map-selected.png'),
  fingerprintCoin: require('../Images/fingerprint-coin.png'),
  fingerprintVerified: require('../Images/fingerprint-verified.png'),
  signUpButton: require('../Images/registration-btn.png'),
  newHeaderImage: require('../Images/header-bkgrd.png'),
  findCare: require('../Images/care-finder.png'),
  eventscalendar: require('../Images/events.png'),
  rxtool: require('../Images/rx-tool.png'),
  findretailcenter: require('../Images/retail-center.png'),
  cliamlistbutton: require('../Images/back-to-list-btn.png'),
  claimdetailheaderred: require('../Images/detail-hdr-bkgrd-red.png'),
  claimdetailheaderyellow: require('../Images/detail-hdr-bkgrd-yellow.png'),
  claimdetailheaderblue: require('../Images/detail-hdr-bkgrd-teal.png'),
  claimlistsearch: require('../Images/search-btn-small.png'),
  datesearch: require('../Images/search-btn-large.png')
}

export default images
