module.exports = {
  environment: 'prod',
  appName: 'Florida Blue Mobile Prod',
  gaTag: 'UA-43067611-3',
  mobApiUrl: 'https://mobapi.bcbsfl.com/mob/api/v1/',
  registrationURL: 'https://registration.bcbsfl.com/ers/api-public/v1/users/',
  forgotPwdURL: 'https://registration.bcbsfl.com/ecir/public/fps.do?channel=mobile&userType=member',
  logoutURL: 'https://logout.bcbsfl.com/logout.fcc',
  webAccessibilityURL: 'https://www.floridablue.com/general/web-accessibility',
  ndnoticeURL: 'https://www.floridablue.com/ndnotice',
  termsOfUseURL: 'https://www.floridablue.com/terms-of-use',
  internetStatementURL: 'https://www.floridablue.com/internet-privacy-statement',
  browseDoctorsURL: 'https://providersearch.floridablue.com/providersearch/pub/index.htm',
  supportURL: 'https://www.floridablue.com/general/contact-us',
  floridaBlueURL: 'https://www.floridablue.com/',
  anotherLanguageURL: 'https://www.floridablue.com/languageservices?_ga=1.102498241.1713434787.1485183405#es',
  mailOrderLearnLink: 'https://mwe.bcbsfl.com/wps/contenthandler/mbs/!ut/p/digest!30_AP8jv7LJcY31ofAxfMg/war/mwe8_base_theme/themes/html/mwe8_base_theme/web/viewer.html?file=https%3A%2F%2Fmwe.bcbsfl.com%2Fwps%2Fwcm%2Fmyconnect%2Fmbs%2Facfb35004e04f4adb575f5b454b86f09%2F5737-A%2520FL_PrimeMail_Brochure%252010-15.pdf%3FMOD%3DAJPERES',
  primeMailOrderLink: 'https://mwe.bcbsfl.com/wps/myportal/mbs/mwe/myaccount/Disclaimer?param1Name=mailOrder&sk=1&nw=1',
  caremarkSpecialty: 'https://mwe.bcbsfl.com/wps/myportal/mbs/mwe/myaccount/Disclaimer?nw=1&param1Name=https://www.caremark.com/wps/portal/SPECIALTY_PHARMACY',
  medicarePlansLink: 'https://www.walgreens.com/topic/s/mail_service_pharmacy_primemail.jsp',
  primeTherapeutics: 'https://mwe.bcbsfl.com/wps/myportal/mbs/mwe/myaccount/Disclaimer?nw=1&param1Name=https://www.primetherapeutics.com/specialty/',
  caremarkHemophilia: 'https://mwe.bcbsfl.com/wps/myportal/mbs/mwe/myaccount/Disclaimer?nw=1&param1Name=https://www.cvsspecialty.com/wps/portal/specialty/patients/drugs-conditions/conditions/hemophilia/!ut/p/a1/jZLLbsIwEEW_xsvGExyC6S4N1KWBQkoDIRuUhwORiB0ZAypfX4O6KH1AvbE8c-5c3ZFxgmOciHRfrVJdSZFuTu_EXXpsFoXgd1xzU_CYH_ivYWgDJQZYuEv443iAv6ppL2gbNY0ICfrE9E9qAzBqMzZ2IBhPu13wHNKfTdgjAer8w_26wQ39M05WG5mdgy5aauSPVjhpUr2-q0QpcYxAyIIjIO0T4ImMUAMoXnLFlbVTRrfWurlHgOBwOFhZnm3LjZXLGkFP5ruaCz2sMpWqdwQTJfdVwdUWgS-FNi0EI16wnSlaTVH-ZrGWW43jy9H4',
  tLCRxSpecialty: 'https://mwe.bcbsfl.com/wps/myportal/mbs/mwe/myaccount/Disclaimer?nw=1&param1Name=http://www.tlcrxpharmacy.com'

}
