// @flow

// leave off @2x/@3x
const images = {
  backButton: require('../Images/back-btn.png'),
  background: require('../Images/bkgrd-gradient.png'),
  clearLogo: require('../Images/login-logo.png'),
  closeButtonGray: require('../Images/close-btn-gray.png'),
  closeIconBlue: require('../Images/close-icon-blue.png'),
  closeIconWhite: require('../Images/close-icon-white.png'),
  clouds: require('../Images/clouds.png'),
  findCare: require('../Images/find-care-img-dashboard.png'),
  findItButton: require('../Images/find-it-btn.png'),
  healthPlan: require('../Images/health-plan-circle-icon.png'),
  hsaBg: require('../Images/hsa-graphic.png'),
  hsaHeader: require('../Images/hsa-hdr.png'),
  iAgree: require('../Images/agree-btn.png'),
  idCardBack: require('../Images/id-card-back.png'),
  idCardFront: require('../Images/id-card-front.png'),
  infoIcon: require('../Images/info-icon-gray.png'),
  loginButton: require('../Images/login-screen-login-btn-blue.png'),
  loginButtonGreen: require('../Images/login-btn-green.png'),
  loginLogo: require('../Images/login-logo.png'),
  loginLogo: require('../Images/login-logo.png'),
  loginNowButton: require('../Images/login-now-btn-dk-blue.png'),
  logo: require('../Images/ir.png'),
  logout: require('../Images/logout-btn-green.png'),
  myPlanbg: require('../Images/myplan-dashboard-bkg.png'),
  nextButton: require('../Images/next-btn.png'),
  nextButtonGreen: require('../Images/next-btn-green.png'),
  regCompletion: require('../Images/reg-complete-hdr.png'),
  regcompletehdr: require('../Images/reg-complete-hdr.png'),
  registrationStep1Hdr: require('../Images/registration-step1-header.png'),
  registrationStep1Hdr: require('../Images/registration-step1-header.png'),
  registrationStep2Hdr: require('../Images/registration-step2-header.png'),
  registrationStep3Hdr: require('../Images/registration-step3-header.png'),
  registrationStep4Hdr: require('../Images/registration-step4-header.png'),
  setupPinButtonGray: require('../Images/setup-pin-btn-gray.png'),
  setupTouchButtonBlue: require('../Images/setup-touch-btn-blue.png'),
  setupTouchButtonGray: require('../Images/setup-touch-btn-gray.png'),
  splashLogo: require('../Images/splash-logo.png'),
  themeHeader: require('../Images/dashboard-hdr.png'),
  themeLogo: require('../Images/theme-logo.png'),
  tileBg: require('../Images/tile_bg.png')
}

export default images
